package Daje::Database::Model::Login;
use Mojo::Base 'Daje::Database::Model::Super::Users', -base, -signatures, -async_await;

# Autogenerated class Sun Feb  9 13:11:20 2025
# This class is generated once. Any over rides or special methods should be put here

# NAME
# ====
#
#      Daje::Database::Model::Login - It's the login class for users
#
#
# REQUIRES
# ========
#
# use Mojo::Base;
# use Daje::Database::Model::Super::Users;
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::Login is logging in users
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.comE<gt>
#
#

use Digest::SHA qw{sha512_base64};

our $VERSION = "0.01";

async sub login_user ($self, $userid, $password) {

        $password = sha512_base64 $password;

        say "Password: " . Dumper($password);
        my $login = venditabant::Model::Login->new(
            pg => $self->pg
        )->login(
            $userid, $password
        );

        my $jwt;
        my $result;

        if($login) {
            #my $json = encode_json($login);
            $jwt = await System::Helpers::Jwt->new()->encode_jwt_p($login);
            $result = {
                userid   => $userid,
                jwt      => $jwt,
                expires  => '',
                support => $login->{support}
            };
        }

        return $result;
}


1;
#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Model::Users


=head1 DESCRIPTION

Autogenerated class Sun Feb  9 13:11:20 2025
This class is generated once. Any over rides or special methods should be put here


=head1 REQUIRES

L<Mojo::Base>


=head1 METHODS


=cut



1;